data = [
    "ASIN",
    "Product ID",
    "Brand",
    "Title",
    "Package Quantity",
    "Amazon Link",
    "Product Group",
    "Sales Rank",
    "Est Sales",
    "Profit",
    "Margin",
    "ROI",
    "Purchase Price",
    "Sell Price",
    "Seller Proceeds",
    "VAT %",
    "VAT $",
    "Inbound Shipping Estimate",
    "Package Dimensions",
    "Package Weight",
    "Amazon Seller",
    "Reviews",
    "Ratings",
    "Total Offers",
    "New FBA Num Offers",
    "New MFN Num Offers",
    "Keepa",
    "CamelCC",
    "Last Run",
    "Item Code",
    "Item Name",
    "Category",
    "Group",
    "Stock",
    "Order",
    "Price GBP",
    "Price EUR",
    "Price USD",
    "Publisher",
    "Language",
    "Commodity Code",
    "Country of Origin",
]

data = [
    ("ASIN", "B098RKWHHZ"),
    ("Product ID", "0045496453459"),
    ("Brand", "Nintendo"),
    ("Title", "Nintendo Switch – OLED Model w/ White Joy-Con"),
    ("Package Quantity", "1"),
    ("Amazon Link", "http://www.amazon.com/dp/B098RKWHHZ"),
    ("Product Group", "Video Games"),
    ("Sales Rank", "12"),
    ("Est Sales", "13\xa0800"),
    ("Profit", "($32,95)"),
    ("Margin", "-9,41%"),
    ("ROI", "-9,52%"),
    ("Purchase Price", "$346,21"),
    ("Sell Price", "$349,99"),
    ("Seller Proceeds", "$313,26"),
    ("VAT %", " 0%"),
    ("VAT $", "$0,00"),
    ("Inbound Shipping Estimate", "$0,00"),
    ("Package Dimensions", "10.16 x 8.15 x 3.82"),
    ("Package Weight", "3,26"),
    ("Amazon Seller", nan),
    ("Reviews", nan),
    ("Ratings", nan),
    ("Total Offers", 20),
    ("New FBA Num Offers", 5.0),
    ("New MFN Num Offers", 3.0),
    ("Keepa", "https://keepa.com/iframe_addon.html#1-0-B098RKWHHZ"),
    ("CamelCC", "https://camelcamelcamel.com/search?sq=B098RKWHHZ"),
    ("Last Run", "06.23.2022 01:13:56 PM"),
    ("Item Code", 106362.0),
    ("Item Name", "Nintendo SwitchOLED Console with White Joy-Con (UK) /Switch"),
    ("Category", "CONSO"),
    ("Group", "Switch"),
    ("Stock", 9.0),
    ("Order", nan),
    ("Price GBP", 280.99),
    ("Price EUR", 327.16),
    ("Price USD", 344.21),
    ("Publisher", "Nintendo"),
    ("Language", nan),
    ("Commodity Code", 9504500000.0),
    ("Country of Origin", "CN"),
]
